### ISSUE TITLE
fetchRef.current is not a function

### ISSUE THREAD

**Issue by coffeemug** [nandorojo/swr-react-native#10]
Thank you for a great library.

I'm using `swr-react-native` with bottom tab navigation (i.e. `createBottomTabNavigator`). Any time I switch back to a tab, I get the following error:

![image](https://user-images.githubusercontent.com/48436/135146093-4514512e-86f7-43ee-b562-99057c4bf9bf.png)

I triple checked all my code and everything *seems* good on my side. What are the conditions under which this error may occur? Or is this a bug in the library?

**Comment by nandorojo** [comment]
Hey, this could be an issue of SWR versions (they deprecated the `revalidate` function)

could you share what your usage looks like? Even a snippet could help

**Comment by nandorojo** [comment]
Oh also, make sure you installed the `@nandorojo/swr-react-native` version

**Comment by coffeemug** [comment]
Thanks for a quick response!

I'm at `@nandorojo/swr-react-native` version 0.1.3 and `swr` version 1.0.1. Should I be using a different version pair? My usage is the default one, I just import `useSWRNative` and then call it instead of `useSWR`. No fanciness:

```js
import useSWRNative from '@nandorojo/swr-react-native';

const MyComponent = () => {
  const { data } = useSWRNative('my_key');
  return (...);
}
```

**Comment by nandorojo** [comment]
K lemme take a look

**Comment by nandorojo** [comment]
Can you try upgrading this library?

**Comment by nandorojo** [comment]
Ah it’s still in beta.

you can use the `@beta` to use SWR v1, I forgot to add that to latest.

`yarn add @nandorojo/swr-react-native@beta`

**Comment by nandorojo** [comment]
Lmk if that works for you, I'll publish to the normal package when I get the chance soon.

**Comment by coffeemug** [comment]
Yes this worked, thank you!

**Comment by coffeemug** [comment]
To clarify, should I be running both swr@beta *and* swr-react-native@beta, or just swr-react-native@beta? Upgrading just swr-react-native@beta worked, but I'm not sure which pair is supposed to be compatible.

Thanks again for making this library. It's so good.

**Comment by nandorojo** [comment]
`@nandorojo/swr-react-native@beta` _should_ be compatible with any 1.x version of `swr`. I originally released it version when `swr` v1 was in beta, so I put it behind the `@beta` flag.

The current `swr@beta` has some nice new features, so you could install that too. But (I think) it shouldn't be necessary. Normal `swr` v1 should work too.

This should work:

```sh
yarn add @nandorojo/swr-react-native@beta swr #swr is v1 stable
```

And so should this:

```sh
yarn add @nandorojo/swr-react-native@beta swr@beta #swr is v1 beta
```

It's possible some of the types don't match up with the latest version of SWR, I'll have to take look. They made a few changes since `1.0.0-beta`, I think. 

For context, my app ([beatgig.com](https://beatgig.com)) is currently still on  `"swr": "1.0.0-beta.10"`, since they added some breaking changes after that and I haven't had time to upgrade it yet. So I can guarantee that version works. And if the pairings I mentioned above don't work smoothly, just lmk, it should be an easy upgrade.

> Thanks again for making this library. It's so good.

Happy to hear it. Glad it's useful.

**Comment by nandorojo** [comment]
Let me know if there are other issues, but this should work now, so I’m going to close it!

If you think others would find the lib useful, always helps to tweet it out (https://twitter.com/fernandotherojo)

**Comment by jetaix** [comment]
Thanks  a lot @nandorojo 🙏

It's works fine with `yarn add @nandorojo/swr-react-native@beta swr@beta`
