### ISSUE TITLE
Drop in replacement via babel alias possible?

### ISSUE THREAD

**Issue by pke** [nandorojo/swr-react-native#23]
I wonder if instead of rewriting all our imports it would also be possible to do define a babel alias instead like "prereact" does for "react".

Has anybody tried this? @nandorojo

**Comment by nandorojo** [comment]
certainly possible. I won't make it a recommendation since they don't export all the same things though. a better suggestion would be to have your own file, like `hooks/use-get` which re-exports useSWR with your own hook name. I find that it's best to wrap library code into your own centralized file so you can always change the function from one place.

**Comment by pke** [comment]
I just tried it, it almost works it just chokes on `swr/infinite` which is not exported by your lib.
We already have a customised swr hook indeed, I will probably hook it into there.
